# Generated by Django 5.1 on 2024-09-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://tse3.mm.bing.net/th?id=OIP.htFK2Pzc1Xpg23Pwi_fezQHaE4&pid=Api&P=0&h=180', max_length=500),
        ),
    ]
